blank_issues_enabled: false
contact_links:
  - name: 邮件联系
    url: mailto:contact@zimin.fan
    about: 通过邮件联系与岷同乐团队
  - name: 籽岷主页
    url: https://space.bilibili.com/686127
    about: 查看籽岷的 Bilibili 主页
